let adSelectors = [];
let observer = null;
let removeAdsTimer = null;

const DEBOUNCE_DELAY_MS = 100;

/**
 * Returns true when a cosmetic rule applies to the current website.
 */
function ruleMatchesCurrentSite(ruleSite, currentHostname) {
    if (ruleSite === "*") {
        return true;
    }

    return (
        currentHostname === ruleSite ||
        currentHostname.endsWith(`.${ruleSite}`)
    );
}

/**
 * Tests a CSS selector before adding it to the active rule set.
 */
function isValidSelector(selector) {
    if (typeof selector !== "string" || selector.trim() === "") {
        return false;
    }

    try {
        document.querySelector(selector);
        return true;
    } catch (error) {
        console.warn(
            `ScamShield skipped invalid selector: ${selector}`,
            error
        );

        return false;
    }
}

/**
 * Loads cosmetic rules generated by convert_filters.py.
 */
async function loadFilters() {
    try {
        const filtersUrl = chrome.runtime.getURL("filters.json");
        const response = await fetch(filtersUrl);

        if (!response.ok) {
            throw new Error(
                `Could not load filters.json: HTTP ${response.status}`
            );
        }

        const filters = await response.json();

        if (!Array.isArray(filters.cosmeticRules)) {
            throw new Error(
                "filters.json does not contain a cosmeticRules array"
            );
        }

        const currentHostname = window.location.hostname
            .toLowerCase()
            .replace(/^www\./, "");

        const matchingSelectors = filters.cosmeticRules
            .filter((rule) => {
                return (
                    rule &&
                    typeof rule.site === "string" &&
                    typeof rule.selector === "string" &&
                    ruleMatchesCurrentSite(
                        rule.site.toLowerCase(),
                        currentHostname
                    )
                );
            })
            .map((rule) => rule.selector.trim())
            .filter(isValidSelector);

        // Remove duplicate selectors.
        adSelectors = [...new Set(matchingSelectors)];

        console.log(
            `ScamShield loaded ${adSelectors.length} cosmetic selectors`
        );
    } catch (error) {
        console.error(
            "ScamShield could not load cosmetic filters:",
            error
        );

        adSelectors = [];
    }
}

/**
 * Removes matching elements from a given DOM root.
 *
 * Searching only newly added elements is much faster than scanning the
 * entire document after every DOM mutation.
 */
function removeAdsFromRoot(root) {
    if (adSelectors.length === 0 || !root) {
        return;
    }

    for (const selector of adSelectors) {
        try {
            /*
             * Remove the root itself when it matches.
             * Element.matches() is unavailable on Document objects.
             */
            if (
                root instanceof Element &&
                root.matches(selector)
            ) {
                root.remove();
                return;
            }

            if (
                root instanceof Document ||
                root instanceof DocumentFragment ||
                root instanceof Element
            ) {
                const suspectedAds =
                    root.querySelectorAll(selector);

                suspectedAds.forEach((element) => {
                    element.remove();
                });
            }
        } catch (error) {
            console.warn(
                `ScamShield skipped selector during page scan: ${selector}`,
                error
            );
        }
    }
}

/**
 * Performs a full-page scan.
 */
function removeAds() {
    removeAdsFromRoot(document);
}

/**
 * Debounces full-page scans so many rapid mutations do not trigger
 * thousands of repeated selector searches.
 */
function scheduleFullScan() {
    clearTimeout(removeAdsTimer);

    removeAdsTimer = setTimeout(() => {
        removeAds();
    }, DEBOUNCE_DELAY_MS);
}

/**
 * Watches the page for dynamically inserted advertisements.
 */
function startObserver() {
    if (observer) {
        observer.disconnect();
    }

    observer = new MutationObserver((mutations) => {
        let shouldScheduleFullScan = false;

        for (const mutation of mutations) {
            for (const addedNode of mutation.addedNodes) {
                if (
                    addedNode instanceof Element ||
                    addedNode instanceof DocumentFragment
                ) {
                    /*
                     * Scan only the newly inserted section first.
                     * This catches most dynamically loaded ads efficiently.
                     */
                    removeAdsFromRoot(addedNode);
                } else {
                    shouldScheduleFullScan = true;
                }
            }
        }

        /*
         * A delayed complete scan catches unusual changes that do not
         * appear as ordinary inserted elements.
         */
        if (shouldScheduleFullScan) {
            scheduleFullScan();
        }
    });

    observer.observe(document.documentElement, {
        childList: true,
        subtree: true
    });
}

/**
 * Starts ScamShield after the generated filter database is loaded.
 */
async function initializeAdBlocker() {
    await loadFilters();

    if (adSelectors.length === 0) {
        console.warn(
            "ScamShield found no cosmetic selectors for this page"
        );
        return;
    }

    removeAds();
    startObserver();
}

initializeAdBlocker();