let adSelectors = [];
let observer = null;
let removeAdsTimer = null;

const DEBOUNCE_DELAY_MS = 100;
const AD_BLOCK_SETTING = "cosmeticBlockerEnabled";
const COSMETIC_COUNT_SETTING = "cosmeticBlockedCount";
const STYLE_ELEMENT_ID = "mailshield-cosmetic-style";
let adBlockerEnabled = true;
let pendingCosmeticCount = 0;
let countFlushTimer = null;


function recordCosmeticBlocks(amount) {
    if (!Number.isFinite(amount) || amount <= 0) return;
    pendingCosmeticCount += amount;
    clearTimeout(countFlushTimer);
    countFlushTimer = setTimeout(async () => {
        const amountToAdd = pendingCosmeticCount;
        pendingCosmeticCount = 0;
        try {
            const stored = await chrome.storage.local.get({ [COSMETIC_COUNT_SETTING]: 0 });
            await chrome.storage.local.set({
                [COSMETIC_COUNT_SETTING]: Number(stored[COSMETIC_COUNT_SETTING] || 0) + amountToAdd
            });
        } catch (error) {
            console.warn("MailShield could not update cosmetic block counter:", error);
        }
    }, 250);
}

async function setCommonCosmeticCss(enabled) {
    document.getElementById(STYLE_ELEMENT_ID)?.remove();
    if (!enabled) return;

    try {
        const response = await fetch(chrome.runtime.getURL("cosmetic.css"));
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const style = document.createElement("style");
        style.id = STYLE_ELEMENT_ID;
        style.textContent = await response.text();
        (document.head || document.documentElement).appendChild(style);
    } catch (error) {
        console.error("MailShield could not load common cosmetic CSS:", error);
    }
}

function stopAdBlocker() {
    observer?.disconnect();
    observer = null;
    clearTimeout(removeAdsTimer);
    document.getElementById(STYLE_ELEMENT_ID)?.remove();
}


/**
 * Returns true when a cosmetic rule applies to the current website.
 */
function ruleMatchesCurrentSite(ruleSite, currentHostname) {
    if (ruleSite === "*") {
        return true;
    }

    return (
        currentHostname === ruleSite ||
        currentHostname.endsWith(`.${ruleSite}`)
    );
}

/**
 * Tests a CSS selector before adding it to the active rule set.
 */
function isValidSelector(selector) {
    if (typeof selector !== "string" || selector.trim() === "") {
        return false;
    }

    try {
        document.querySelector(selector);
        return true;
    } catch (error) {
        console.warn(
            `ScamShield skipped invalid selector: ${selector}`,
            error
        );

        return false;
    }
}

/**
 * Loads cosmetic rules generated by convert_filters.py.
 */
async function loadFilters() {
    try {
        const filtersUrl = chrome.runtime.getURL("filters.json");
        const response = await fetch(filtersUrl);

        if (!response.ok) {
            throw new Error(
                `Could not load filters.json: HTTP ${response.status}`
            );
        }

        const filters = await response.json();

        if (!Array.isArray(filters.cosmeticRules)) {
            throw new Error(
                "filters.json does not contain a cosmeticRules array"
            );
        }

        const currentHostname = window.location.hostname
            .toLowerCase()
            .replace(/^www\./, "");

        const matchingSelectors = filters.cosmeticRules
            .filter((rule) => {
                return (
                    rule &&
                    typeof rule.site === "string" &&
                    typeof rule.selector === "string" &&
                    ruleMatchesCurrentSite(
                        rule.site.toLowerCase(),
                        currentHostname
                    )
                );
            })
            .map((rule) => rule.selector.trim())
            .filter(isValidSelector);

        // Remove duplicate selectors.
        adSelectors = [...new Set(matchingSelectors)];

        console.log(
            `ScamShield loaded ${adSelectors.length} cosmetic selectors`
        );
    } catch (error) {
        console.error(
            "ScamShield could not load cosmetic filters:",
            error
        );

        adSelectors = [];
    }
}

/**
 * Removes matching elements from a given DOM root.
 *
 * Searching only newly added elements is much faster than scanning the
 * entire document after every DOM mutation.
 */
function removeAdsFromRoot(root) {
    if (!adBlockerEnabled || adSelectors.length === 0 || !root) {
        return;
    }

    for (const selector of adSelectors) {
        try {
            /*
             * Remove the root itself when it matches.
             * Element.matches() is unavailable on Document objects.
             */
            if (
                root instanceof Element &&
                root.matches(selector)
            ) {
                root.remove();
                recordCosmeticBlocks(1);
                return;
            }

            if (
                root instanceof Document ||
                root instanceof DocumentFragment ||
                root instanceof Element
            ) {
                const suspectedAds = root.querySelectorAll(selector);
                let removedCount = 0;

                suspectedAds.forEach((element) => {
                    if (element.isConnected) {
                        element.remove();
                        removedCount += 1;
                    }
                });

                recordCosmeticBlocks(removedCount);
            }
        } catch (error) {
            console.warn(
                `ScamShield skipped selector during page scan: ${selector}`,
                error
            );
        }
    }
}

/**
 * Performs a full-page scan.
 */
function removeAds() {
    removeAdsFromRoot(document);
}

/**
 * Debounces full-page scans so many rapid mutations do not trigger
 * thousands of repeated selector searches.
 */
function scheduleFullScan() {
    clearTimeout(removeAdsTimer);

    removeAdsTimer = setTimeout(() => {
        removeAds();
    }, DEBOUNCE_DELAY_MS);
}

/**
 * Watches the page for dynamically inserted advertisements.
 */
function startObserver() {
    if (observer) {
        observer.disconnect();
    }

    observer = new MutationObserver((mutations) => {
        let shouldScheduleFullScan = false;

        for (const mutation of mutations) {
            for (const addedNode of mutation.addedNodes) {
                if (
                    addedNode instanceof Element ||
                    addedNode instanceof DocumentFragment
                ) {
                    /*
                     * Scan only the newly inserted section first.
                     * This catches most dynamically loaded ads efficiently.
                     */
                    removeAdsFromRoot(addedNode);
                } else {
                    shouldScheduleFullScan = true;
                }
            }
        }

        /*
         * A delayed complete scan catches unusual changes that do not
         * appear as ordinary inserted elements.
         */
        if (shouldScheduleFullScan) {
            scheduleFullScan();
        }
    });

    observer.observe(document.documentElement, {
        childList: true,
        subtree: true
    });
}

/**
 * Starts cosmetic ad blocking when the saved setting is enabled.
 */
async function initializeAdBlocker() {
    const stored = await chrome.storage.local.get({ [AD_BLOCK_SETTING]: true });
    adBlockerEnabled = stored[AD_BLOCK_SETTING];
    await setCommonCosmeticCss(adBlockerEnabled);

    if (!adBlockerEnabled) return;

    await loadFilters();
    if (adSelectors.length === 0) {
        console.warn("MailShield found no cosmetic selectors for this page");
        return;
    }

    removeAds();
    startObserver();
}

chrome.storage.onChanged.addListener(async (changes, areaName) => {
    if (areaName !== "local" || !changes[AD_BLOCK_SETTING]) return;

    adBlockerEnabled = changes[AD_BLOCK_SETTING].newValue !== false;
    if (adBlockerEnabled) {
        await setCommonCosmeticCss(true);
        if (adSelectors.length === 0) await loadFilters();
        removeAds();
        startObserver();
    } else {
        stopAdBlocker();
    }
});

initializeAdBlocker();
